//! Reproduction scaffolds (roadmap 5.6).
//!
//! ADR-025 deferred this behind the gate, and it arrives with the [`SafeWriter`] jail rather
//! than before it: the jail is the precondition for writing into a project, never a follow-up.
//!
//! # What this generates, and what it does not
//!
//! A *scaffold*: a test file that names the finding, quotes its evidence, and fails until
//! somebody writes the assertion. Not a test that reproduces the defect — nothing here knows
//! how to do that, and a generated test that passes because it asserts nothing is worse than
//! no test, because it looks like coverage.
//!
//! The templates are deterministic per `(finding kind, framework)`. No model is involved, in
//! keeping with the rule that holds everywhere else in this system: the platform produces
//! evidence, and reasoning belongs to the agent that reads it.

use crate::safe_writer::{JailError, SafeWriter};
use std::path::{Path, PathBuf};

/// What a scaffold needs to know about the finding it is for.
#[derive(Debug, Clone)]
pub struct Subject {
    pub uid: String,
    pub title: String,
    /// Where the finding says the problem is.
    pub evidence: Vec<String>,
    /// The symbol under suspicion, if the finding named one.
    pub anchor: Option<String>,
}

/// Which test framework to write for, from the detected build system.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Framework {
    JUnit,
    Jest,
    Pytest,
    CargoTest,
}

impl Framework {
    pub fn for_build_system(build_system: Option<&str>) -> Option<Framework> {
        match build_system {
            Some("gradle") | Some("maven") => Some(Framework::JUnit),
            Some("npm") | Some("pnpm") | Some("yarn") => Some(Framework::Jest),
            Some("pip") | Some("poetry") | Some("uv") => Some(Framework::Pytest),
            Some("cargo") => Some(Framework::CargoTest),
            // Refusing beats guessing: a scaffold in the wrong language is a file somebody has
            // to find and delete.
            _ => None,
        }
    }

    fn extension(self) -> &'static str {
        match self {
            Framework::JUnit => "java",
            Framework::Jest => "test.ts",
            Framework::Pytest => "py",
            Framework::CargoTest => "rs",
        }
    }
}

fn slug(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c);
        } else if !out.ends_with('_') {
            out.push('_');
        }
    }
    out.trim_matches('_').to_string()
}

/// The scaffold's text. Deterministic: the same finding produces the same bytes.
pub fn render(subject: &Subject, framework: Framework) -> String {
    let name = slug(&subject.uid);
    let evidence = subject
        .evidence
        .iter()
        .map(|e| format!("//   {e}"))
        .collect::<Vec<_>>()
        .join("\n");
    let anchor = subject.anchor.as_deref().unwrap_or("the symbol above");
    let header = format!(
        "// Generated by nexus for {uid}: {title}\n\
         //\n\
         // This scaffold does not reproduce the defect. It names it, quotes its evidence, and\n\
         // fails until somebody writes the assertion — a generated test that passes because it\n\
         // asserts nothing is worse than no test, because it looks like coverage.\n\
         //\n\
         // Evidence:\n{evidence}\n\
         //\n\
         // Under suspicion: {anchor}\n",
        uid = subject.uid,
        title = subject.title,
    );

    match framework {
        Framework::JUnit => format!(
            "{header}\n\
             import org.junit.jupiter.api.Test;\n\
             import static org.junit.jupiter.api.Assertions.fail;\n\n\
             class {name}Test {{\n\
             \x20   @Test\n\
             \x20   void reproduces() {{\n\
             \x20       fail(\"write the assertion that shows {uid}\");\n\
             \x20   }}\n\
             }}\n",
            uid = subject.uid
        ),
        Framework::Jest => format!(
            "{header}\n\
             describe('{uid}', () => {{\n\
             \x20 it('reproduces', () => {{\n\
             \x20   throw new Error('write the assertion that shows {uid}');\n\
             \x20 }});\n\
             }});\n",
            uid = subject.uid
        ),
        Framework::Pytest => format!(
            "{header}\n\
             import pytest\n\n\n\
             def test_reproduces_{name}():\n\
             \x20   pytest.fail(\"write the assertion that shows {uid}\")\n",
            uid = subject.uid
        ),
        Framework::CargoTest => format!(
            "{header}\n\
             #[test]\n\
             fn reproduces_{name}() {{\n\
             \x20   panic!(\"write the assertion that shows {uid}\");\n\
             }}\n",
            uid = subject.uid
        ),
    }
}

/// Write the scaffold into the jail. The only path this crate ever writes to.
pub fn write(
    project_root: &Path,
    subject: &Subject,
    framework: Framework,
) -> Result<PathBuf, JailError> {
    let writer = SafeWriter::at(project_root)?;
    let relative = format!("{}.{}", slug(&subject.uid), framework.extension());
    writer.write(&relative, &render(subject, framework))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn subject() -> Subject {
        Subject {
            uid: "BUG-3".into(),
            title: "@Transactional on a non-public method".into(),
            evidence: vec!["src/mn/pay/PaymentService.java:48".into()],
            anchor: Some("mn.pay.PaymentService#pay".into()),
        }
    }

    #[test]
    fn a_scaffold_fails_until_somebody_writes_the_assertion() {
        // A generated test that passes because it asserts nothing looks like coverage, which
        // is worse than having none.
        for f in [
            Framework::JUnit,
            Framework::Jest,
            Framework::Pytest,
            Framework::CargoTest,
        ] {
            let text = render(&subject(), f);
            assert!(
                text.contains("write the assertion"),
                "{f:?} produced a scaffold that does not fail"
            );
            assert!(text.contains("BUG-3"), "{f:?} does not name the finding");
            assert!(
                text.contains("PaymentService.java:48"),
                "{f:?} drops the evidence"
            );
        }
    }

    #[test]
    fn the_same_finding_always_produces_the_same_bytes() {
        // Deterministic per (finding, framework). No model, like everything else here.
        let a = render(&subject(), Framework::JUnit);
        for _ in 0..5 {
            assert_eq!(render(&subject(), Framework::JUnit), a);
        }
    }

    #[test]
    fn an_unknown_build_system_gets_no_scaffold_rather_than_the_wrong_one() {
        assert_eq!(
            Framework::for_build_system(Some("cargo")),
            Some(Framework::CargoTest)
        );
        assert_eq!(Framework::for_build_system(Some("bazel")), None);
        assert_eq!(Framework::for_build_system(None), None);
    }

    #[test]
    fn it_is_written_inside_the_jail_and_nowhere_else() {
        let root = std::env::temp_dir().join(format!("nexus-repro-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).expect("mkdir");
        let path = write(&root, &subject(), Framework::CargoTest).expect("write");
        assert!(
            path.starts_with(
                root.join(".nexus")
                    .join("generated-tests")
                    .canonicalize()
                    .expect("root")
            ),
            "{path:?}"
        );
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn a_hostile_finding_id_cannot_steer_the_path() {
        // A uid is data. If one could contain a separator the jail would be the only thing
        // between it and the source tree, and one mechanism is not enough for this.
        let mut s = subject();
        s.uid = "../../etc/passwd".into();
        assert_eq!(slug(&s.uid), "etc_passwd");
    }
}
