/* eslint-disable */
// THIS FILE IS GENERATED by graphql-codegen. Do not edit.
// Nothing here was written by a person and nothing here can be changed by one — the whole
// file is regenerated from order.graphqls on every build.
export type Maybe<T> = T | null;
export type Scalars = { ID: string; String: string; Float: number; Boolean: boolean };
export type Order = {
  __typename?: "Order";
  id: Scalars["ID"];
  reference: Scalars["String"];
  totalAmount: Scalars["Float"];
  status: Scalars["String"];
};
export type Query = { __typename?: "Query"; orders: Array<Order>; order?: Maybe<Order> };
export type OrdersQueryVariables = Record<string, never>;
export type OrdersQuery = { __typename?: "Query"; orders: Array<Order> };
